### ISSUE TITLE
ColumnsResizer extension doesn't works 

### ISSUE THREAD

**Issue by ns3115neha** [ThomasSiegmund/D3TableFilter#20]
ColumnsResizer extension doesn't works

**Comment by ThomasSiegmund** [comment]
True, as stated in the news. This is currently  [not supported](https://github.com/koalyptus/TableFilter/issues/311) in Tablefilter.

**Comment by ThomasSiegmund** [comment]
A new implementation of column resizing based on the [jQuery colResizable plugin ](http://www.bacubacu.com/colresizable/) has been added. There is also a test app in the examples. Please give it a try.

**Comment by afpapa2** [comment]
I have two issues related column sizing.

1) By adding a vector of col_widths in tableprops (i.e. col_widths = c('100px', '100px', '100px', '200px')) I can change the initial widths within the Rstudio Rshiny application, but when I launch it via the browser the initial column widths set by me seem to be completely ignored

2) In trying to figure out the above problem I added an action button to the renderD3tf so that I could re-render it on command. It seems that the behavior of the column resizer switched from "overflow" to another resize option (even though when I print the TableProps it still shows "overflow". After resizing and rerendering enough times the columns started to scale proportionally instead of independently.

**Comment by ThomasSiegmund** [comment]
Sorry, this is a bit too complex. Please open separate issues and add reproducible examples.

Thanks

T.
